{
  pkgs,
  lib,
  config,
  inputs,
  ...
}:
let
  # --- lxml 4.9.4 compatibility pin -------------------------------------
  # Plone 6.0.10 pins lxml = 4.9.4. That release ships no macOS arm64 wheel
  # on PyPI (x86_64 only), so on this machine uv/pip must build it from the
  # sdist. The build compiles against the libxml2 found in this shell, and
  # lxml 4.9.4's pre-generated Cython C code predates an API change made in
  # libxml2 2.12.0: xmlStructuredErrorFunc now takes `const xmlError *`
  # (verified against upstream headers v2.11.9 vs v2.12.0). Result against
  # the rolling nixpkgs libxml2 (2.15.4): 8 "incompatible function pointer
  # types" errors and a failed wheel build. Fix: give the shell the last
  # pre-2.12 pair, libxml2 2.11.5 + libxslt 1.1.38.
  #
  # How the versions were found (nixpkgs-multiverse indexes every version of
  # every package from every nixpkgs revision, https://nixmultiverse.com):
  #   nix eval --raw 'github:fzakaria/nixpkgs-multiverse#versions.libxml2."2.11.5".version'
  #   nix eval 'github:fzakaria/nixpkgs-multiverse#versions.libxslt' --apply builtins.attrNames
  # Cross-check that the pair is ABI-matched (each attr is evaluated from the
  # historical nixpkgs revision that shipped it):
  #   libxslt 1.1.38 <- nixpkgs 666fc80e (nixos-23.11 era), which builds it
  #   against libxml2 2.11.5 exactly:
  #   nix eval --raw github:NixOS/nixpkgs/666fc80e7b2afb570462423cb0e1cf1a3a34fedd#libxml2.version
  multiverse = inputs.nixpkgs-multiverse.legacyPackages.${pkgs.stdenv.system};
in
{

  packages = [
    multiverse.versions.libxml2."2.11.5"
    multiverse.versions.libxslt."1.1.38"
    pkgs.just
    # Pillow 6.2.2 (Plone 5.2.15 pin) has no cp39 wheel at all (predates
    # Python 3.9) -> sdist build; its setup.py hard-requires libjpeg + zlib
    # headers, discovered only via compiler search paths. CPATH/LIBRARY_PATH
    # below point clang at these store paths.
    pkgs.libjpeg_turbo
    pkgs.zlib
    # cffi 1.14.6 (Zope 4.8.1 pin for Plone 5.2.8 — kept for Python 3.5
    # compat there) also predates macOS arm64 wheels -> sdist build of
    # _cffi_backend.c, which needs ffi.h (libffi). Same discovery mechanism
    # as Pillow: CPATH/LIBRARY_PATH below. (cffi 1.15+ ships arm64 wheels,
    # which is why 5.2.9+ never hits this.)
    pkgs.libffi
  ];

  # Header/library discovery for sdist builds (Pillow's old setup.py does not
  # use pkg-config). clang reads CPATH for includes and forwards
  # LIBRARY_PATH as -L to the linker; nixpkgs dylibs carry absolute install
  # names, so nothing is needed at runtime.
  env.CPATH = "${pkgs.libjpeg_turbo.dev}/include:${pkgs.zlib.dev}/include:${pkgs.libffi.dev}/include";
  # (note: libjpeg_turbo's default output is "bin" — reference .out for libs)
  env.LIBRARY_PATH = "${pkgs.libjpeg_turbo.out}/lib:${pkgs.zlib.out}/lib:${pkgs.libffi.out}/lib";

  # Old-C-extensions vs modern Clang ----------------------------------------
  # Zope 4.8.10 (Plone 5.2.15) pins AccessControl = 4.4, which has no macOS
  # arm64 wheel -> sdist build. Its hand-written cAccessControl.c still has
  # positional `NULL, /* tp_print */` initializers; since Python 3.8 that
  # struct slot is tp_vectorcall_offset (Py_ssize_t), so clang diagnoses
  # "incompatible pointer to integer conversion initializing 'Py_ssize_t'
  # with 'void *'". Clang >= 16 made -Wint-conversion a hard error by default
  # (this shell ships clang 21), turning the formerly-benign warning into a
  # build failure. The code is semantically fine (NULL -> 0 offset, as
  # intended for years) — silence the diagnostic for sdist builds. distutils
  # /setuptools merges the CFLAGS env var into extension compile lines, and
  # uv/zc.buildout pass the shell environment through to build subprocesses.
  env.CFLAGS = "-Wno-int-conversion";

  # Second lxml-4.9.4-on-modern-tooling fix: its setup.py only declares
  # extras_require (cssselect, html5, ...) when `import pkg_resources`
  # succeeds in the *build* env. uv's isolated sdist builds use a current
  # setuptools where pkg_resources is removed, silently stripping the extras
  # (breaks plone.protect's `lxml[cssselect]` at buildout time AND
  # pkg_resources.require() at Zope startup). Constrain the build env to
  # Plone 6.0.10's own setuptools pin; uv reads UV_BUILD_CONSTRAINT (singular)
  # and zc.buildout passes it through to its uv subprocesses.
  env.UV_BUILD_CONSTRAINT = "${config.devenv.root}/build-constraints.txt";

  # The constraints file itself is generated by devenv (files option,
  # https://devenv.sh/files/): created on shell entry, removed on cleanup.
  # Content = Plone 6.0.10's own setuptools pin
  # (https://dist.plone.org/release/6.0.10/versions.cfg).
  files."build-constraints.txt".text = ''
    setuptools==69.0.3
  '';

  # devenv.sh/languages/
  languages = {
    python.enable = true;
    python.uv.enable = true;
    python.version = "3.9";
  };

  # See full reference at https://devenv.sh/reference/options/
}
